### ISSUE TITLE
[bug] Merge conflict marker in Program.cs blocks build

### ISSUE THREAD

**Issue by markgar** [markgar/stretto-20260226-143251#171]
What failed: The file src/Stretto.Api/Program.cs contains a merge conflict marker `<<<<<<< HEAD` at line 20 (without corresponding `=======` and `>>>>>>>` markers), which causes CS8300 build error in all projects that reference Stretto.Api. This was introduced in commit 30aac0f by the [validator] agent.\n\nSteps to reproduce:\n1. Run `dotnet build Stretto.sln`\n2. Build fails with: `src/Stretto.Api/Program.cs(20,1): error CS8300: Merge conflict marker encountered`\n\nMilestone: Members — API
